version: '3.8'

services:
  backend:
    build: .
    container_name: trading-backend
    ports:
      - "8282:8282"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app/src
      - DOCKER_ENV=1
    restart: unless-stopped
    networks:
      - trading-network

  frontend:
    build: ./frontend
    container_name: trading-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge